// Данные из файла "годовой план робототехника.xlsx" — 85 уроков

const PLAN_ID = "robotics-2026";

const PLAN_META = {
  id: PLAN_ID,
  title: "Робототехника 2026–2027",
  totalLessons: 85,
};

const LESSONS = [
  {
    id: 1,
    category: "Автомобили, мотоциклы",
    name: "Лимузин",
    pages: 44,
    link: "https://lego.a1gtn.ru/instructions/limuzin-480.pdf",
  },
  {
    id: 2,
    category: "Автомобили, мотоциклы",
    name: "Гоночный автомобиль",
    pages: 38,
    link: "https://lego.a1gtn.ru/instructions/gonochnyi-avtomobil-280.pdf",
  },
  {
    id: 3,
    category: "Автомобили, мотоциклы",
    name: "Монстртрак",
    pages: 52,
    link: "https://lego.a1gtn.ru/instructions/monstrtrak-290.pdf",
  },
  {
    id: 4,
    category: "Автомобили, мотоциклы",
    name: "Эвакуатор",
    pages: 42,
    link: "https://lego.a1gtn.ru/instructions/evakuator-351.pdf",
  },
  {
    id: 5,
    category: "Автомобили, мотоциклы",
    name: "Мотоциклист",
    pages: 57,
    link: "https://lego.a1gtn.ru/instructions/mototsikl-292.pdf",
  },
  {
    id: 6,
    category: "Автомобили, мотоциклы",
    name: "Внедорожник",
    pages: 62,
    link: "https://lego.a1gtn.ru/instructions/vnedorozhnik-285.pdf",
  },
  {
    id: 7,
    category: "Автомобили, мотоциклы",
    name: "Багги",
    pages: 28,
    link: "https://lego.a1gtn.ru/instructions/baggi-472.pdf",
  },
  {
    id: 8,
    category: "Военная техника",
    name: "Самолёт",
    pages: 64,
    link: "https://lego.a1gtn.ru/instructions/samolet-331.pdf",
  },
  {
    id: 9,
    category: "Военная техника",
    name: "Вертолёт",
    pages: 65,
    link: "https://lego.a1gtn.ru/instructions/vertolet-321.pdf",
  },
  {
    id: 10,
    category: "Военная техника",
    name: "Катапульта",
    pages: 46,
    link: "https://lego.a1gtn.ru/instructions/katapulta-264.pdf",
  },
  {
    id: 11,
    category: "Военная техника",
    name: "Радар",
    pages: 30,
    link: "https://lego.a1gtn.ru/instructions/radar-227.pdf",
  },
  {
    id: 12,
    category: "Динозавры",
    name: "Зауропод",
    pages: 43,
    link: "https://lego.a1gtn.ru/instructions/zauropod-75.pdf",
  },
  {
    id: 13,
    category: "Динозавры",
    name: "Плезиозавр",
    pages: 67,
    link: "https://lego.a1gtn.ru/instructions/pleziozavr-61.pdf",
  },
  {
    id: 14,
    category: "Динозавры",
    name: "Птеродактиль",
    pages: 31,
    link: "https://lego.a1gtn.ru/instructions/pterodaktil-77.pdf",
  },
  {
    id: 15,
    category: "Динозавры",
    name: "Сложный птеродактиль",
    pages: 46,
    link: "https://lego.a1gtn.ru/instructions/pterodaktil-78.pdf",
  },
  {
    id: 16,
    category: "Животные",
    name: "Головастик",
    pages: 29,
    link: "https://lego.a1gtn.ru/instructions/golovastik-436.pdf",
  },
  {
    id: 17,
    category: "Животные",
    name: "Жираф",
    pages: "46 (из-за дубликатов 92)",
    link: "https://lego.a1gtn.ru/instructions/zhiraf-127.pdf",
  },
  {
    id: 18,
    category: "Животные",
    name: "Кинг-Конг",
    pages: 60,
    link: "https://lego.a1gtn.ru/instructions/king-kong-76.pdf",
  },
  {
    id: 19,
    category: "Животные",
    name: "Кот и мышь",
    pages: 42,
    link: "https://lego.a1gtn.ru/instructions/kot-i-mysh-136.pdf",
  },
  {
    id: 20,
    category: "Животные",
    name: "Крокодил",
    pages: 34,
    link: "https://lego.a1gtn.ru/instructions/krokodil-138.pdf",
  },
  {
    id: 21,
    category: "Животные",
    name: "Лошадь",
    pages: "33 (из-за дубликатов 67)",
    link: "https://lego.a1gtn.ru/instructions/loshad-146.pdf",
  },
  {
    id: 22,
    category: "Животные",
    name: "Обезьяна",
    pages: 37,
    link: "https://lego.a1gtn.ru/instructions/obezyana-154.pdf",
  },
  {
    id: 23,
    category: "Животные",
    name: "Улитка",
    pages: 49,
    link: "https://lego.a1gtn.ru/instructions/ulitka-182.pdf",
  },
  {
    id: 24,
    category: "Животные",
    name: "Черепаха",
    pages: 30,
    link: "https://lego.a1gtn.ru/instructions/cherepaha-190.pdf",
  },
  {
    id: 25,
    category: "Животные",
    name: "Собака",
    pages: 44,
    link: "https://lego.a1gtn.ru/instructions/sobaka-168.pdf",
  },
  {
    id: 26,
    category: "Корабли",
    name: "Лодка",
    pages: 30,
    link: "https://lego.a1gtn.ru/instructions/lodka-223.pdf",
  },
  {
    id: 27,
    category: "Корабли",
    name: "Катер (сложный)",
    pages: 67,
    link: "https://lego.a1gtn.ru/instructions/kater-217.pdf",
  },
  {
    id: 28,
    category: "Корабли",
    name: "Катер (лёгкий)",
    pages: 29,
    link: "https://lego.a1gtn.ru/instructions/kater-218.pdf",
  },
  {
    id: 29,
    category: "Корабли",
    name: "Катамаран исследователь",
    pages: 62,
    link: "https://lego.a1gtn.ru/instructions/katamaran-issledovatel-577.pdf",
  },
  {
    id: 30,
    category: "Космос",
    name: "Грузовой космический корабль",
    pages: 55,
    link: "https://lego.a1gtn.ru/instructions/gruzovoi-kosmicheskiy-korabl-562.pdf",
  },
  {
    id: 31,
    category: "Космос",
    name: "Исследовательский спутник",
    pages: 30,
    link: "https://lego.a1gtn.ru/instructions/issledovatelskiy-sputnik-561.pdf",
  },
  {
    id: 32,
    category: "Космос",
    name: "Планетаход",
    pages: 40,
    link: "https://lego.a1gtn.ru/instructions/planetohod-232.pdf",
  },
  {
    id: 33,
    category: "Космос",
    name: "Робот искатель",
    pages: 50,
    link: "https://lego.a1gtn.ru/instructions/robot-iskatel-564.pdf",
  },
  {
    id: 34,
    category: "Космос",
    name: "Солнечная система",
    pages: 53,
    link: "https://lego.a1gtn.ru/instructions/model-solnechnoi-sistemy-581.pdf",
  },
  {
    id: 35,
    category: "Космос",
    name: "Космический лифт",
    pages: 46,
    link: "https://lego.a1gtn.ru/instructions/kosmicheskiy-lift-559.pdf",
  },
  {
    id: 36,
    category: "Люди",
    name: "Валентинка",
    pages: 54,
    link: "https://lego.a1gtn.ru/instructions/valentinka-374.pdf",
  },
  {
    id: 37,
    category: "Люди",
    name: "Лыжник",
    pages: 44,
    link: "https://lego.a1gtn.ru/instructions/lyzhnik-52.pdf",
  },
  {
    id: 38,
    category: "Люди",
    name: "Индеец",
    pages: 52,
    link: "https://lego.a1gtn.ru/instructions/indeets-202.pdf",
  },
  {
    id: 39,
    category: "Люди",
    name: "Родео",
    pages: 40,
    link: "https://lego.a1gtn.ru/instructions/rodeo-405.pdf",
  },
  {
    id: 40,
    category: "Люди",
    name: "Рыцарский турнир",
    pages: 63,
    link: "https://lego.a1gtn.ru/instructions/rytsarskiy-turnir-418.pdf",
  },
  {
    id: 41,
    category: "Люди",
    name: "Танец",
    pages: 31,
    link: "https://lego.a1gtn.ru/instructions/tantsy-415.pdf",
  },
  {
    id: 42,
    category: "Люди",
    name: "Циркачи",
    pages: 44,
    link: "https://lego.a1gtn.ru/instructions/tsirkach-420.pdf",
  },
  {
    id: 43,
    category: "Люди",
    name: "Шахтёр",
    pages: 34,
    link: "https://lego.a1gtn.ru/instructions/shahter-421.pdf",
  },
  {
    id: 44,
    category: "Люди",
    name: "Кузнецы",
    pages: 60,
    link: "https://lego.a1gtn.ru/instructions/kuznetsy-390.pdf",
  },
  {
    id: 45,
    category: "Люди",
    name: "Велосипедисты",
    pages: 41,
    link: "https://lego.a1gtn.ru/instructions/velosipedisty-382.pdf",
  },
  {
    id: 46,
    category: "Механизмы",
    name: "Автоматические ворота",
    pages: 46,
    link: "https://lego.a1gtn.ru/instructions/avtomaticheskie-vorota-25.pdf",
  },
  {
    id: 47,
    category: "Механизмы",
    name: "Бензопила",
    pages: 23,
    link: "https://lego.a1gtn.ru/instructions/benzopila-352.pdf",
  },
  {
    id: 48,
    category: "Механизмы",
    name: "Банкомат",
    pages: 33,
    link: "https://lego.a1gtn.ru/instructions/bankomat-368.pdf",
  },
  {
    id: 49,
    category: "Механизмы",
    name: "Вентилятор (сложный)",
    pages: 51,
    link: "https://lego.a1gtn.ru/instructions/ventilyator-376.pdf",
  },
  {
    id: 50,
    category: "Механизмы",
    name: "Вентилятор (лёгкий)",
    pages: 32,
    link: "https://lego.a1gtn.ru/instructions/ventilyator-404.pdf",
  },
  {
    id: 51,
    category: "Механизмы",
    name: "Весы",
    pages: 30,
    link: "https://lego.a1gtn.ru/instructions/vesy-378.pdf",
  },
  {
    id: 52,
    category: "Механизмы",
    name: "Карусель (лёгкий)",
    pages: 30,
    link: "https://lego.a1gtn.ru/instructions/karusel-203.pdf",
  },
  {
    id: 53,
    category: "Механизмы",
    name: "Карусель (сложный)",
    pages: 41,
    link: "https://lego.a1gtn.ru/instructions/karusel-205.pdf",
  },
  {
    id: 54,
    category: "Механизмы",
    name: "Лифт",
    pages: 28,
    link: "https://lego.a1gtn.ru/instructions/lift-391.pdf",
  },
  {
    id: 55,
    category: "Механизмы",
    name: "Пресс",
    pages: 26,
    link: "https://lego.a1gtn.ru/instructions/press-92.pdf",
  },
  {
    id: 56,
    category: "Механизмы",
    name: "Светофор и шлагбаум",
    pages: 64,
    link: "https://lego.a1gtn.ru/instructions/svetofor-i-shlagbaum-389.pdf",
  },
  {
    id: 57,
    category: "Механизмы",
    name: "Швейная машина",
    pages: 24,
    link: "https://lego.a1gtn.ru/instructions/shveinaya-mashina-96.pdf",
  },
  {
    id: 58,
    category: "Насекомые",
    name: "Муравей",
    pages: 38,
    link: "https://lego.a1gtn.ru/instructions/muravei-151.pdf",
  },
  {
    id: 59,
    category: "Насекомые",
    name: "Муха",
    pages: 58,
    link: "https://lego.a1gtn.ru/instructions/muha-549.pdf",
  },
  {
    id: 60,
    category: "Насекомые",
    name: "Паук (сложный)",
    pages: 62,
    link: "https://lego.a1gtn.ru/instructions/pauk-156.pdf",
  },
  {
    id: 61,
    category: "Насекомые",
    name: "Паук (лёгкий)",
    pages: 38,
    link: "https://lego.a1gtn.ru/instructions/pauk-157.pdf",
  },
  {
    id: 62,
    category: "Насекомые",
    name: "Жук",
    pages: 27,
    link: "https://lego.a1gtn.ru/instructions/zhuk-477.pdf",
  },
  {
    id: 63,
    category: "Новогодние",
    name: "Летающий Санта",
    pages: 63,
    link: "https://lego.a1gtn.ru/instructions/letauschiy-santa-85.pdf",
  },
  {
    id: 64,
    category: "Новогодние",
    name: "Лыжник Санта",
    pages: 54,
    link: "https://lego.a1gtn.ru/instructions/lyzhnik-santa-86.pdf",
  },
  {
    id: 65,
    category: "Новогодние",
    name: "Новогодняя ёлка",
    pages: 56,
    link: "https://lego.a1gtn.ru/instructions/novogodnyaya-elka-429.pdf",
  },
  {
    id: 66,
    category: "Новогодние",
    name: "Олень Рудольф",
    pages: 44,
    link: "https://lego.a1gtn.ru/instructions/olen-rudolf-82.pdf",
  },
  {
    id: 67,
    category: "Птицы",
    name: "Птица машет",
    pages: 19,
    link: "https://lego.a1gtn.ru/instructions/ptitsa-mashet-krylyami-165.pdf",
  },
  {
    id: 68,
    category: "Птицы",
    name: "Мама и птенчик",
    pages: 44,
    link: "https://lego.a1gtn.ru/instructions/ptitsy-167.pdf",
  },
  {
    id: 69,
    category: "Роботы",
    name: "Шагающий робот",
    pages: 37,
    link: "https://lego.a1gtn.ru/instructions/shagauschiy-robot-42.pdf",
  },
  {
    id: 70,
    category: "Роботы",
    name: "Робот защитник",
    pages: 55,
    link: "https://lego.a1gtn.ru/instructions/robot-zaschitnik-568.pdf",
  },
  {
    id: 71,
    category: "Вертолёт!Самолёт!",
    name: "Вертолёт (сложный)",
    pages: 28,
    link: "https://lego.a1gtn.ru/instructions/vertolet-312.pdf",
  },
  {
    id: 72,
    category: "Вертолёт!Самолёт!",
    name: "Вертолёт (лёгкий)",
    pages: 28,
    link: "https://lego.a1gtn.ru/instructions/vertolet-319.pdf",
  },
  {
    id: 73,
    category: "Вертолёт!Самолёт!",
    name: "Самолёт",
    pages: 35,
    link: "https://lego.a1gtn.ru/instructions/samolet-328.pdf",
  },
  {
    id: 74,
    category: "Спец техника",
    name: "Башенный кран (сложный)",
    pages: 57,
    link: "https://lego.a1gtn.ru/instructions/bashennyi-kran-26.pdf",
  },
  {
    id: 75,
    category: "Спец техника",
    name: "Вилочный погрузчик (лёгкий)",
    pages: 23,
    link: "https://lego.a1gtn.ru/instructions/vilochnyi-pogruzchik-348.pdf",
  },
  {
    id: 76,
    category: "Спец техника",
    name: "Вилочный погрузчик (сложный)",
    pages: 61,
    link: "https://lego.a1gtn.ru/instructions/vilochnyi-pogruzchik-337.pdf",
  },
  {
    id: 77,
    category: "Спец техника",
    name: "Культиватор",
    pages: 22,
    link: "https://lego.a1gtn.ru/instructions/kultivator-253.pdf",
  },
  {
    id: 78,
    category: "Спец техника",
    name: "Комбайн",
    pages: 45,
    link: "https://lego.a1gtn.ru/instructions/kombain-249.pdf",
  },
  {
    id: 79,
    category: "Спец техника",
    name: "Башенный кран (лёгкий)",
    pages: 26,
    link: "https://lego.a1gtn.ru/instructions/podemnyi-kran-334.pdf",
  },
  {
    id: 80,
    category: "Спец техника",
    name: "Рухлилка",
    pages: 53,
    link: "https://lego.a1gtn.ru/instructions/ryhlilka-254.pdf",
  },
  {
    id: 81,
    category: "Спец техника",
    name: "Уборочная машина",
    pages: 45,
    link: "https://lego.a1gtn.ru/instructions/uborochnaya-mashina-304.pdf",
  },
  {
    id: 82,
    category: "Спорт",
    name: "Штангист",
    pages: 49,
    link: "https://lego.a1gtn.ru/instructions/shtangist-58.pdf",
  },
  {
    id: 83,
    category: "Спорт",
    name: "Гимнаст",
    pages: 24,
    link: "https://lego.a1gtn.ru/instructions/gimnast-476.pdf",
  },
  {
    id: 84,
    category: "Транспорт",
    name: "Автобус (лёгкий)",
    pages: 39,
    link: "https://lego.a1gtn.ru/instructions/avtobus-270.pdf",
  },
  {
    id: 85,
    category: "Транспорт",
    name: "Автобус (сложный)",
    pages: 56,
    link: "https://lego.a1gtn.ru/instructions/avtobus-271.pdf",
  },
];

const CATEGORIES = [...new Set(LESSONS.map((l) => l.category))].sort((a, b) =>
  a.localeCompare(b, "ru"),
);

function getLessonById(id) {
  return LESSONS.find((l) => l.id === Number(id));
}
